# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

# This workflow will install Deno then run Deno lint and test.
# For more information see: https://github.com/denoland/setup-deno

name: CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

permissions:
  contents: read

jobs:
  profile-deno:
    runs-on: ubuntu-latest

    steps:
      - name: setup repo
        uses: actions/checkout@v3

      - name: setup Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x

      - name: Run profile
        run: deno task profile

  unit-test-deno:
    runs-on: ubuntu-latest

    steps:
      - name: setup repo
        uses: actions/checkout@v3

      - name: setup Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x

      # - name: Verify formatting
      #   run: deno fmt --check

      - name: run linter
        run: deno lint

      - name: run tests
        run: deno task test

  test-run-bun:
    runs-on: ubuntu-latest

    steps:
      - name: setup repo
        uses: actions/checkout@v3

      - name: setup Bun.sh
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: bun intall
        run: bun install

      - name: bun run
        run: npm run test:bun

    after_script:
      - pkill bun

  test-run-wrangler:
    runs-on: ubuntu-latest

    steps:
      - name: setup repo
        uses: actions/checkout@v3

      - name: npm intall
        run: npm install

      - name: setup Wrangler
        run: npm install -g wrangler

      - name: wrangler dev
        run: npm run test:cfw

    after_script:
      - pkill node
