# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

# This workflow will install Deno then run Deno lint and test.
# For more information see: https://github.com/denoland/setup-deno

name: CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

permissions:
  contents: read

jobs:
  profile-deno:
    runs-on: ubuntu-latest

    steps:
      - name: setup repo
        uses: actions/checkout@v3

      - name: setup pnpm
        run: npm install -g pnpm

      - name: setup packages
        run: pnpm install

      - name: setup Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x

      - name: Run profile
        run: pnpm profile:deno

  profile-bun:
    runs-on: ubuntu-latest

    steps:
      - name: setup repo
        uses: actions/checkout@v3

      - name: setup pnpm
        run: npm install -g pnpm

      - name: setup packages
        run: pnpm install

      - name: setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Run profile
        run: pnpm profile:bun

  unit-test-deno:
    runs-on: ubuntu-latest

    steps:
      - name: setup repo
        uses: actions/checkout@v3

      - name: setup pnpm
        run: npm install -g pnpm

      - name: setup Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x

      # - name: Verify formatting
      #   run: deno fmt --check

      - name: run linter
        run: deno lint

      - name: run tests
        run: pnpm test
